// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	accept_votes "github.com/go-server-dev/src/app/usecase/accept_votes"
	mock "github.com/stretchr/testify/mock"
)

// Presenter is an autogenerated mock type for the Presenter type
type Presenter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *Presenter) Execute(_a0 accept_votes.Output) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(accept_votes.Output) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
