// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	start_talk "github.com/go-server-dev/src/app/usecase/start_talk"
	mock "github.com/stretchr/testify/mock"
)

// Presenter is an autogenerated mock type for the Presenter type
type Presenter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *Presenter) Execute(_a0 start_talk.Output) {
	_m.Called(_a0)
}

// FinishTalk provides a mock function with given fields: _a0
func (_m *Presenter) FinishTalk(_a0 start_talk.FinishTalkOutput) {
	_m.Called(_a0)
}
