// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	start_talk "github.com/go-server-dev/src/app/usecase/start_talk"
	mock "github.com/stretchr/testify/mock"
)

// Presenter is an autogenerated mock type for the Presenter type
type Presenter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *Presenter) Execute(_a0 start_talk.Output) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(start_talk.Output) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FinishTalk provides a mock function with given fields: _a0
func (_m *Presenter) FinishTalk(_a0 start_talk.FinishTalkOutput) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(start_talk.FinishTalkOutput) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
