// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/go-server-dev/src/app/domain"
	mock "github.com/stretchr/testify/mock"
)

// ReadOnlyRepository is an autogenerated mock type for the ReadOnlyRepository type
type ReadOnlyRepository struct {
	mock.Mock
}

// FindGameMasterByGroupID provides a mock function with given fields: _a0
func (_m *ReadOnlyRepository) FindGameMasterByGroupID(_a0 string) (*domain.GameMaster, error) {
	ret := _m.Called(_a0)

	var r0 *domain.GameMaster
	if rf, ok := ret.Get(0).(func(string) *domain.GameMaster); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GameMaster)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
