// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	start_talk "github.com/go-server-dev/src/app/usecase/start_talk"
	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Excute provides a mock function with given fields: _a0
func (_m *UseCase) Excute(_a0 start_talk.Input) start_talk.Output {
	ret := _m.Called(_a0)

	var r0 start_talk.Output
	if rf, ok := ret.Get(0).(func(start_talk.Input) start_talk.Output); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(start_talk.Output)
	}

	return r0
}
