version: "3"
services:
  # LINEbot
  bot:
    build:
      # Dockerfile名を変更しているためcontextとdockerfileを用いてDockerfileの場所を指定
      context: ./bot
      dockerfile: DockerfileForDev
    ports:
      - "3010:3010"
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.utf8"
      LC_ALL: "ja_JP.utf8"
    volumes:
      - ../:/go/src/github.com/go-server-dev
    working_dir: /go/src/github.com/go-server-dev
  # DB
  mongo:
    image: mongo:3-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    # volumes:
    #   - ./db:/data/db
    #   - ./configdb:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
  # インメモリDB
  redis:
    image: redis:6.0
